// <auto-generated />
using System;
using GestionZapatillas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionZapatillas.Data.Migrations
{
    [DbContext(typeof(ShoeDbContext))]
    partial class ShoeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionZapatillas.Entities.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("BrandId");

                    b.HasIndex("BrandName")
                        .IsUnique()
                        .HasDatabaseName("IX_Brands_BrandName");

                    b.ToTable("Brands", (string)null);

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            Active = true,
                            BrandName = "Adidas",
                            Country = "Alemania"
                        },
                        new
                        {
                            BrandId = 2,
                            Active = true,
                            BrandName = "Nike",
                            Country = "Estados Unidos"
                        },
                        new
                        {
                            BrandId = 3,
                            Active = true,
                            BrandName = "Topper",
                            Country = "Argentina"
                        },
                        new
                        {
                            BrandId = 4,
                            Active = true,
                            BrandName = "Reebok",
                            Country = "Estados Unidos"
                        });
                });

            modelBuilder.Entity("GestionZapatillas.Entities.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("GenreId");

                    b.HasIndex("GenreName")
                        .IsUnique()
                        .HasDatabaseName("IX_Genres_GenreName");

                    b.ToTable("Genres", (string)null);

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Active = true,
                            GenreName = "Masculino"
                        },
                        new
                        {
                            GenreId = 2,
                            Active = true,
                            GenreName = "Femenino"
                        },
                        new
                        {
                            GenreId = 3,
                            Active = true,
                            GenreName = "Unisex"
                        });
                });

            modelBuilder.Entity("GestionZapatillas.Entities.ShoeSize", b =>
                {
                    b.Property<int>("ShoeSizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoeSizeId"));

                    b.Property<int>("QuantityInStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ShoeId")
                        .HasColumnType("int");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.HasKey("ShoeSizeId");

                    b.HasIndex("SizeId");

                    b.HasIndex("ShoeId", "SizeId")
                        .IsUnique()
                        .HasDatabaseName("IX_ShoeSizes_ShoeId_SizeId");

                    b.ToTable("ShoeSizes", (string)null);
                });

            modelBuilder.Entity("GestionZapatillas.Entities.Size", b =>
                {
                    b.Property<int>("SizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizeId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("SizeNumber")
                        .HasColumnType("decimal(3,1)");

                    b.HasKey("SizeId");

                    b.HasIndex("SizeNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Sizes_SizeNumber");

                    b.ToTable("Sizes", (string)null);

                    b.HasData(
                        new
                        {
                            SizeId = 1,
                            Active = true,
                            SizeNumber = 28.0m
                        },
                        new
                        {
                            SizeId = 2,
                            Active = true,
                            SizeNumber = 28.5m
                        },
                        new
                        {
                            SizeId = 3,
                            Active = true,
                            SizeNumber = 29.0m
                        },
                        new
                        {
                            SizeId = 4,
                            Active = true,
                            SizeNumber = 29.5m
                        },
                        new
                        {
                            SizeId = 5,
                            Active = true,
                            SizeNumber = 30.0m
                        },
                        new
                        {
                            SizeId = 6,
                            Active = true,
                            SizeNumber = 30.5m
                        },
                        new
                        {
                            SizeId = 7,
                            Active = true,
                            SizeNumber = 31.0m
                        },
                        new
                        {
                            SizeId = 8,
                            Active = true,
                            SizeNumber = 31.5m
                        },
                        new
                        {
                            SizeId = 9,
                            Active = true,
                            SizeNumber = 32.0m
                        },
                        new
                        {
                            SizeId = 10,
                            Active = true,
                            SizeNumber = 32.5m
                        },
                        new
                        {
                            SizeId = 11,
                            Active = true,
                            SizeNumber = 33.0m
                        },
                        new
                        {
                            SizeId = 12,
                            Active = true,
                            SizeNumber = 33.5m
                        },
                        new
                        {
                            SizeId = 13,
                            Active = true,
                            SizeNumber = 34.0m
                        },
                        new
                        {
                            SizeId = 14,
                            Active = true,
                            SizeNumber = 34.5m
                        },
                        new
                        {
                            SizeId = 15,
                            Active = true,
                            SizeNumber = 35.0m
                        },
                        new
                        {
                            SizeId = 16,
                            Active = true,
                            SizeNumber = 35.5m
                        },
                        new
                        {
                            SizeId = 17,
                            Active = true,
                            SizeNumber = 36.0m
                        },
                        new
                        {
                            SizeId = 18,
                            Active = true,
                            SizeNumber = 36.5m
                        },
                        new
                        {
                            SizeId = 19,
                            Active = true,
                            SizeNumber = 37.0m
                        },
                        new
                        {
                            SizeId = 20,
                            Active = true,
                            SizeNumber = 37.5m
                        },
                        new
                        {
                            SizeId = 21,
                            Active = true,
                            SizeNumber = 38.0m
                        },
                        new
                        {
                            SizeId = 22,
                            Active = true,
                            SizeNumber = 38.5m
                        },
                        new
                        {
                            SizeId = 23,
                            Active = true,
                            SizeNumber = 39.0m
                        },
                        new
                        {
                            SizeId = 24,
                            Active = true,
                            SizeNumber = 39.5m
                        },
                        new
                        {
                            SizeId = 25,
                            Active = true,
                            SizeNumber = 40.0m
                        },
                        new
                        {
                            SizeId = 26,
                            Active = true,
                            SizeNumber = 40.5m
                        },
                        new
                        {
                            SizeId = 27,
                            Active = true,
                            SizeNumber = 41.0m
                        },
                        new
                        {
                            SizeId = 28,
                            Active = true,
                            SizeNumber = 41.5m
                        },
                        new
                        {
                            SizeId = 29,
                            Active = true,
                            SizeNumber = 42.0m
                        },
                        new
                        {
                            SizeId = 30,
                            Active = true,
                            SizeNumber = 42.5m
                        },
                        new
                        {
                            SizeId = 31,
                            Active = true,
                            SizeNumber = 43.0m
                        },
                        new
                        {
                            SizeId = 32,
                            Active = true,
                            SizeNumber = 43.5m
                        },
                        new
                        {
                            SizeId = 33,
                            Active = true,
                            SizeNumber = 44.0m
                        },
                        new
                        {
                            SizeId = 34,
                            Active = true,
                            SizeNumber = 44.5m
                        },
                        new
                        {
                            SizeId = 35,
                            Active = true,
                            SizeNumber = 45.0m
                        },
                        new
                        {
                            SizeId = 36,
                            Active = true,
                            SizeNumber = 45.5m
                        },
                        new
                        {
                            SizeId = 37,
                            Active = true,
                            SizeNumber = 46.0m
                        },
                        new
                        {
                            SizeId = 38,
                            Active = true,
                            SizeNumber = 46.5m
                        },
                        new
                        {
                            SizeId = 39,
                            Active = true,
                            SizeNumber = 47.0m
                        },
                        new
                        {
                            SizeId = 40,
                            Active = true,
                            SizeNumber = 47.5m
                        },
                        new
                        {
                            SizeId = 41,
                            Active = true,
                            SizeNumber = 48.0m
                        },
                        new
                        {
                            SizeId = 42,
                            Active = true,
                            SizeNumber = 48.5m
                        },
                        new
                        {
                            SizeId = 43,
                            Active = true,
                            SizeNumber = 49.0m
                        },
                        new
                        {
                            SizeId = 44,
                            Active = true,
                            SizeNumber = 49.5m
                        },
                        new
                        {
                            SizeId = 45,
                            Active = true,
                            SizeNumber = 50.0m
                        },
                        new
                        {
                            SizeId = 46,
                            Active = true,
                            SizeNumber = 50.5m
                        });
                });

            modelBuilder.Entity("GestionZapatillas.Entities.Sport", b =>
                {
                    b.Property<int>("SportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SportId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SportName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SportId");

                    b.HasIndex("SportName")
                        .IsUnique()
                        .HasDatabaseName("IX_Sports_SportName");

                    b.ToTable("Sports", (string)null);

                    b.HasData(
                        new
                        {
                            SportId = 1,
                            Active = true,
                            SportName = "Fútbol"
                        },
                        new
                        {
                            SportId = 2,
                            Active = true,
                            SportName = "Running"
                        },
                        new
                        {
                            SportId = 3,
                            Active = true,
                            SportName = "Outdoor"
                        },
                        new
                        {
                            SportId = 4,
                            Active = true,
                            SportName = "Urban"
                        },
                        new
                        {
                            SportId = 5,
                            Active = true,
                            SportName = "Training"
                        },
                        new
                        {
                            SportId = 6,
                            Active = true,
                            SportName = "Tenis"
                        });
                });

            modelBuilder.Entity("GestionZapatillas.Entities.SportShoe", b =>
                {
                    b.Property<int>("ShoeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoeId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.HasKey("ShoeId");

                    b.HasIndex("BrandId");

                    b.HasIndex("GenreId");

                    b.HasIndex("SportId");

                    b.ToTable("Shoes", (string)null);
                });

            modelBuilder.Entity("GestionZapatillas.Entities.ShoeSize", b =>
                {
                    b.HasOne("GestionZapatillas.Entities.SportShoe", "SportShoe")
                        .WithMany("ShoeSizes")
                        .HasForeignKey("ShoeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionZapatillas.Entities.Size", "Size")
                        .WithMany("ShoeSizes")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Size");

                    b.Navigation("SportShoe");
                });

            modelBuilder.Entity("GestionZapatillas.Entities.SportShoe", b =>
                {
                    b.HasOne("GestionZapatillas.Entities.Brand", "Brand")
                        .WithMany("SportShoes")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionZapatillas.Entities.Genre", "Genre")
                        .WithMany("SportShoes")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionZapatillas.Entities.Sport", "Sport")
                        .WithMany("SportShoes")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Genre");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("GestionZapatillas.Entities.Brand", b =>
                {
                    b.Navigation("SportShoes");
                });

            modelBuilder.Entity("GestionZapatillas.Entities.Genre", b =>
                {
                    b.Navigation("SportShoes");
                });

            modelBuilder.Entity("GestionZapatillas.Entities.Size", b =>
                {
                    b.Navigation("ShoeSizes");
                });

            modelBuilder.Entity("GestionZapatillas.Entities.Sport", b =>
                {
                    b.Navigation("SportShoes");
                });

            modelBuilder.Entity("GestionZapatillas.Entities.SportShoe", b =>
                {
                    b.Navigation("ShoeSizes");
                });
#pragma warning restore 612, 618
        }
    }
}
